version: "3.9"

networks:
  hub:
    labels:
      space.jetbrains.on-premises.version: "2023.3.23062"
      space.jetbrains.on-premises.select: "true"
# volumes:
#   hub-data:
#     labels:
#       hub.jetbrains.on-premises.version: "2023.3.23062"
#       hub.jetbrains.on-premises.select: "true"
#   hub-conf:
#     labels:
#       hub.jetbrains.on-premises.version: "2023.3.23062"
#       hub.jetbrains.on-premises.select: "true"
#   hub-logs:
#     labels:
#       hub.jetbrains.on-premises.version: "2023.3.23062"
#       hub.jetbrains.on-premises.select: "true"
#   hub-backups:
#     labels:
#       hub.jetbrains.on-premises.version: "2023.3.23062"
#       hub.jetbrains.on-premises.select: "true"

services:
  hub:
    user: 13001:13001
    image: "jetbrains/hub:2023.3.23062"
    labels:
      hub.jetbrains.on-premises.version: "2023.3.23062"
      hub.jetbrains.on-premises.select: "true"
    # deploy:
    #   replicas: 1
    #   update_config:
    #     parallelism: 1
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure
    hostname: hub
    ports:
      - 8080:8080
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl --fail http://0.0.0.0:${APP_LANGSERVICE_INTERNAL_PORT}/healthcheck || exit 1",
    #     ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s
    volumes:
      # - hub-data:/opt/hub/data
      # - hub-conf:/opt/hub/conf
      # - hub-logs:/opt/hub/logs
      # - hub-backups:/opt/hub/backups
      - ./data:/opt/hub/data
      - ./conf:/opt/hub/conf
      - ./logs:/opt/hub/logs
      - ./backups:/opt/hub/backups
    networks:
      hub:
        aliases:
          - hub
