apiVersion: v2
name: kubernetes-stateful-chart
description: A Generic Helm chart for a stateful Kubernetes application
type: application
version: 0.1.3
appVersion: 1.0.0
icon: https://avatars.githubusercontent.com/u/878437?s=200&v=4
home: https://jetbrains.com/
annotations:
  category: Infrastructure
keywords:
  - jetbrains
  - template
maintainers:
  - name: JetBrains
    url: https://www.jetbrains.com/support
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
