apiVersion: v2
name: kube-prometheus-operator
description: A Helm chart for the Prometheus Monitoring Stack in Kubernetes
type: application
version: 56.21.1
appVersion: v0.71.2
kubeVersion: ">=1.19.0-0"
icon: https://avatars.githubusercontent.com/u/878437?s=200&v=4
home: https://jetbrains.com/
annotations:
  category: Infrastructure
keywords:
  - jetbrains
  - prometheus
maintainers:
  - name: JetBrains
    url: https://www.jetbrains.com/support
dependencies:
  - name: kube-prometheus-stack
    alias: spec
    repository: https://prometheus-community.github.io/helm-charts
    version: 56.21.1
