apiVersion: v2
name: kube-metrics-server
description: A Helm chart for the Kubernetes Metrics Server
type: application
version: 3.12.0
appVersion: 0.7.0
icon: https://avatars.githubusercontent.com/u/878437?s=200&v=4
home: https://jetbrains.com/
annotations:
  category: Infrastructure
keywords:
  - jetbrains
  - kubernetes
  - metrics-server
  - metrics
maintainers:
  - name: JetBrains
    url: https://www.jetbrains.com/support
dependencies:
  - name: metrics-server
    alias: spec
    repository: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.12.0
