apiVersion: v2
name: kube-external-secrets
description: A Helm chart for the External Secrets in Kubernetes
type: application
version: 0.10.3
appVersion: 0.10.3
icon: https://avatars.githubusercontent.com/u/878437?s=200&v=4
home: https://jetbrains.com/
annotations:
  category: Infrastructure
keywords:
  - jetbrains
  - kubernetes
  - kubernetes-external-secrets
  - secrets
maintainers:
  - name: JetBrains
    url: https://www.jetbrains.com/support
dependencies:
  - name: external-secrets
    alias: spec
    repository: https://charts.external-secrets.io
    version: 0.10.3
