apiVersion: v2
name: kube-github-runners
description: A Helm chart for deploying GitHub Runners in Kubernetes
type: application
version: 0.9.3
appVersion: 0.9.3
kubeVersion: ">=1.19.0-0"
icon: https://avatars.githubusercontent.com/u/878437?s=200&v=4
home: https://jetbrains.com/
annotations:
  category: Infrastructure
keywords:
  - jetbrains
  - github
  - continuous-integration
  - runners
  - ark
maintainers:
  - name: JetBrains
    url: https://www.jetbrains.com/support
dependencies:
  - name: gha-runner-scale-set-controller
    alias: controller
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.9.3
  - name: gha-runner-scale-set
    alias: runners
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.9.3
